services:
  app:
    image: bdc2026:latest
    pull_policy: never
    volumes:
      - ./data:/app/data
      - ./test/output:/app/output
      - ./temp:/app/temp
    working_dir: /app
    command: /bin/bash /app/data/run.sh
    privileged: true
    mem_limit: 16g
    memswap_limit: 16g
    cpus: 10.0
